# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 828387b12c49ce2fbc013c0d11530a9516cc116ef07de55dc2f9d3e0e6146628de5d048f69a39fc20b82a7c1d4da557124d8eefcc0e94d0d0a7af74e1edf41cf

test:
  secret_key_base: 1df8e673b29b91b6731379839ada901eeda21d561180a322284414766fbc5df26c3eeaf28421fd47bda1deae28629e446d1010a3445d6a3b1752616fb9bd484b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
